name: Mirror to Arrow GitHub Organization

on: [push, delete] # Runs whenever you push new code or delete a branch

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetches all history for all branches and tags
          persist-credentials: false # Prevent checkout token from overriding mirror auth

      - name: Mirror to Target
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          # Replace with your destination repo URL
          target_repo_url: https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/arrow-data-ai/Arrow-NetApp-Enterprise-RAG.git